[project]
name = "notes"
version = "0.1.0"
description = ""
authors = [{ name = "Chenxing Luo" }]
requires-python = ">=3.10,<4"
dependencies = [
    "jinja2-time>=0.2,<0.3",
    "markdown-captions>=2.1.1,<3",
    "mdx-truly-sane-lists>=1.2,<2",
    "mkdocs>=1.2.3,<2",
    "mkdocs-blogging",
    "mkdocs-compile-sass",
    "mkdocs-jinja2-load-extensions",
    "mkdocs-minify-plugin>=0.5,<0.6",
    "mkdocs-subpages",
    "mkdocs-wikilinks-enabler",
    "pygments>=2.11.2,<3",
    "pymdown-extensions>=11.0.1,<12",
]

[tool.uv]
package = false

[tool.uv.sources]
mkdocs-blogging = { path = "plugins/mkdocs-blogging", editable = true }
mkdocs-compile-sass = { path = "plugins/mkdocs-compile-sass", editable = true }
mkdocs-jinja2-load-extensions = { path = "plugins/mkdocs-jinja2-load-extensions", editable = true }
mkdocs-subpages = { path = "plugins/mkdocs-subpages", editable = true }
mkdocs-wikilinks-enabler = { path = "plugins/mkdocs-wikilinks-enabler", editable = true }
